### ISSUE TITLE
no devices in disk tab

### ISSUE THREAD

**Issue by kapouer** [Ory0n/Resource_Monitor#41]
The Disk tab doesn't show devices.
The menu stays at 0|0.

(I have three disks /dev/sda,b,c)

 - OS: debian/bookworm
 - Version: 17 on gnome 42.1

Harddisk LED gnome extension works but I'd like to get rid of it in favor of this one :)

**Comment by 0ry0n** [comment]
If you open prefs, is the disk list empty?

**Comment by kapouer** [comment]
![image](https://user-images.githubusercontent.com/131406/169048125-a08bee72-55ea-49e3-960d-f9669ebc4af2.png)

**Comment by 0ry0n** [comment]
Please check in `/var/log/syslog` if it gives you this error:
`gnome-shell [x]: JS ERROR: Error: df: /run/user/1000/doc: Operation not permitted...`
My extension uses df to get partition information.
It has already happened in the past that in unstable versions of linux it gives this error.
It is not due to a Resource_Monitor problem.
Thanks for using Resource_Monitor. :)

**Comment by kapouer** [comment]
Indeed, it's a bug in xdg-desktop-portal, which mounts /run/user/1000/doc
